### PR TITLE
Replace RSS feed for users with simple webscrape to get all videos

### PR DESCRIPTION
**Pull request by gageirwin**
Since the RSS feed is limited to only the last 24 posts I implemented a page scraper instead. This scraper will go though all pages of a use and return a list of direct links to all the videos recorded by proxitok.

I did not implement it but the same thing could be done for trending, would be almost identical function, but you would need to set some sort of limit on how many videos/pages it scrapes or it will keep scraping and never return.

### CODE REVIEW

**Comment by gageirwin** [comment]
Should note I did not test it with MPV but downloads worked fine and so should MPV.

**Comment by ovosimpatico** [comment]
That's awesome! I tried doing something similar, but I was trying to scrape TikTok own page rather than proxitok, which wasn't going well.

I left some comments on `byuser.py` for you. Just logging stuff.

I'll test it as soon as possible, but the code looks good!

**Comment by ovosimpatico** [comment]
I tested playback using MPV, and it works great!
Also tested downloading and it is perfect.

One thing to note is that on larger accounts, web scraping can take a significant ammount of time, even on a fast connection. An account with 418 videos took 30s-40s to be scraped on a Gigabit connection for me.

Using `print("Obtaining URLs - this can take a while.")` before starting the Web scraping would really help on this matter

**Comment by gageirwin** [comment]
> Using `print("Obtaining URLs - this can take a while.")` before starting the Web scraping would really help on this matter

If you want I can calculate the amount of pages that will be scraped and can print "Gathering posts from page X/X" so you can better tell how long it will take.

**Comment by ovosimpatico** [comment]
> > Using `print("Obtaining URLs - this can take a while.")` before starting the Web scraping would really help on this matter
> 
> If you want I can calculate the amount of pages that will be scraped and can print "Gathering posts from page X/X" so you can better tell how long it will take.

That would be awesome!

**Comment by gageirwin** [comment]
I just did a tested using a requests.Session object and I was a able to do a user with 2554 video (around 110 pages) in 17.2 seconds. That being the case I think the warning is better suited to not spam tones of messages. Just a heads up something I noticed is that proxitok can be missing some videos, not the fault of the scraper.

**Comment by gageirwin** [comment]
Implemented scraper function for trending videos. You will need to add inputs in the main.py to request the user for how many trending videos they want, default is 24.

**Comment by ovosimpatico** [comment]
Everything works well and fixes the 24 video limitation. Thanks for your contribution.

**Pull request merged**
